// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzevxfszgnbkssuejypu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZXZ4ZnN6Z25ia3NzdWVqeXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTU2NzYsImV4cCI6MjA2MTA5MTY3Nn0.OLXVBtjRwzEq9cdv4wryzkBW5qFvptAsniNF8hKxOIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);